### ISSUE TITLE
周轩熠 二面作答

### ISSUE THREAD

**Issue by dyxg** [QSCTech/2022-Autumn-Round-Two#10]
作答题目
[What-is-JPEG](https://github.com/dyxg/What-is-JPEG)

注意事项：
代码文件为IO.h ,algorithm.h, main.cpp
public repo

希望在9.30下午早些时间面试

**Comment by YasyaKarasu** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
