### ISSUE TITLE
张逸航 二面作答

### ISSUE THREAD

**Issue by dfwwr** [QSCTech/2022-Autumn-Round-Two#11]
作答题目
[What-is-JPEG](https://github.com/dfwwr/picture)  

注意事项：  
代码在pic1.cpp中，文档在summary.md中，函数解释在explain.md中  
备注：希望在9.29晚课后面试，谢谢。

**Comment by YasyaKarasu** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
