### ISSUE TITLE
蔡信诚  二面作答

### ISSUE THREAD

**Issue by xxxUUc** [QSCTech/2022-Autumn-Round-Two#12]
作答题目
[Q&A](https://github.com/xxxUUc/1)

注意事项：
代码在Q&A.html,script.js,styles文件夹里，文档在readme.md里，已添加负责人为协作
备注：想要29晚上（什么时候都行）面试

**Comment by Ag2SO4pro** [comment]
我们已有权限检视您的仓库，感谢参加求是潮 2022 秋纳二面，预祝面试顺利~
