### ISSUE TITLE
王若鹏 二面作答

### ISSUE THREAD

**Issue by daseinonism** [QSCTech/2022-Autumn-Round-Two#13]
h5-games 
代码文件为：
[background.jpg](https://github.com/daseinonism/daseinonism.github.io/blob/main/background.jpg)
[drawall.js](https://github.com/daseinonism/daseinonism.github.io/blob/main/drawall.js)
[style.css](https://github.com/daseinonism/daseinonism.github.io/blob/main/style.css)
[work12.html](https://github.com/daseinonism/daseinonism.github.io/blob/main/work12.html)
[yep.mp3](https://github.com/daseinonism/daseinonism.github.io/blob/main/yep.mp3)
[zju.png](https://github.com/daseinonism/daseinonism.github.io/blob/main/zju.png)
[zju2.png](https://github.com/daseinonism/daseinonism.github.io/blob/main/zju2.png)
作答文件为：
[面试作答.txt](https://github.com/daseinonism/daseinonism.github.io/blob/main/%E9%9D%A2%E8%AF%95%E4%BD%9C%E7%AD%94.txt)

**Comment by daseinonism** [comment]
网页布置：
https://daseinonism.github.io/work12.html

**Comment by ADSR1042** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
