### ISSUE TITLE
任飞扬 二面作答

### ISSUE THREAD

**Issue by FLesic** [QSCTech/2022-Autumn-Round-Two#14]
h5-game
作答题目：
[1.css](https://github.com/FLesic/h5game/blob/main/h5GAME-%E4%BB%BB%E9%A3%9E%E6%89%AC/1.css) 
[2.js](https://github.com/FLesic/h5game/blob/main/h5GAME-%E4%BB%BB%E9%A3%9E%E6%89%AC/2.js) 
[h5game.html](https://github.com/FLesic/h5game/blob/main/h5GAME-%E4%BB%BB%E9%A3%9E%E6%89%AC/h5game-formal.html) 
[问答以及心得体会](https://github.com/FLesic/h5game/blob/main/h5GAME-%E4%BB%BB%E9%A3%9E%E6%89%AC/%E9%97%AE%E9%A2%98%E5%92%8C%E5%9B%9E%E7%AD%94%E4%BB%A5%E5%8F%8A%E5%BF%83%E5%BE%97%E4%BD%93%E4%BC%9A.docx) 
注意事项：
这些个文件都在h5-game任飞扬的文件夹中。
心得体会是word文件，点击View raw下载。
请全部下载好后打开html文件进行游玩！
希望能够安排在9.30下午早些进行面试

**Comment by FLesic** [comment]
请全部下载好后打开html文件进行游玩！

**Comment by ADSR1042** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
