### ISSUE TITLE
胡扬 二面作答

### ISSUE THREAD

**Issue by 1sleepearly** [QSCTech/2022-Autumn-Round-Two#15]
作答题目：
[Cyber-Prisoner](https://github.com/QSCTech/2022-Autumn-Round-Two/tree/main/Cyber-Prisoner)

注意事项：
代码在[main]/[Cyber-Prisoner接收端.cpp](https://github.com/1sleepearly/Cyber-Prisoner/blob/main/Cyber-Prisoner%E6%8E%A5%E6%94%B6%E7%AB%AF.cpp)和[main]/[Cyber-Prisoner服务器.c](https://github.com/1sleepearly/Cyber-Prisoner/blob/main/Cyber-Prisoner%E6%9C%8D%E5%8A%A1%E5%99%A8.c)，文档在[main]/[README.md](https://github.com/1sleepearly/Cyber-Prisoner/blob/main/README.md)

**Comment by YasyaKarasu** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
