### ISSUE TITLE
宋俊翰 二面作答

### ISSUE THREAD

**Issue by ZEntrosein** [QSCTech/2022-Autumn-Round-Two#18]
作答题目：
[Q&A](https://github.com/ZEntrosein/2022-Autumn-Round-Two-myresult)

注意事项：
代码在/html/index.html，css在/html/style.css，js在/html/script.js，文档在/html/心得.md

**Comment by Ag2SO4pro** [comment]
我们已有权限检视您的仓库，感谢参加求是潮 2022 秋纳二面，预祝面试顺利~
