### ISSUE TITLE
石嘉炜 二面作答

### ISSUE THREAD

**Issue by CitadelLan** [QSCTech/2022-Autumn-Round-Two#19]
作答题目：
[h5game](https://github.com/CitadelLan/Qsc2nd/tree/main)

注意事项：
代码在主页面上的h5game.html；文档在思维导图/H5Game.jpg。

**Comment by ADSR1042** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
