### ISSUE TITLE
陈宇轩二面作答

### ISSUE THREAD

**Issue by OOOYX** [QSCTech/2022-Autumn-Round-Two#2]
作答题目：
h5-game

注意事项：
代码在[github.io]/[ChenYuxuan-QSC]/别踩黄块/，文档在[github.io]/[ChenYuxuan-QSC]/Questions.txt

**Comment by ADSR1042** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
