### ISSUE TITLE
徐旸 二面作答

### ISSUE THREAD

**Issue by Xycharm** [QSCTech/2022-Autumn-Round-Two#20]
作答题目：
[What-is-JPEG](https://github.com/QSCTech/2022-Autumn-Round-Two/tree/main/What-is-JPEG) 
注意事项：
代码在Repository/master，文档在README.md

**Comment by Xycharm** [comment]
https://gitee.com/Xychar/repository/tree/master

**Comment by IsshikiHugh** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
