### ISSUE TITLE
黄唯展二面作答

### ISSUE THREAD

**Issue by frcs7** [QSCTech/2022-Autumn-Round-Two#23]
作答题目：
[What-is-JPEG](https://github.com/QSCTech/2022-Autumn-Round-Two/tree/main/What-is-JPEG)

注意事项：
代码在[jpeg](https://github.com/frcs7/jpeg)中master下的example1.cpp和DCT.h，文档在README.md和log.md

**Comment by chenyanzz** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
