### ISSUE TITLE
黄志远 二面作答

### ISSUE THREAD

**Issue by seashoresky** [QSCTech/2022-Autumn-Round-Two#25]
作答题目：
[RandomCredit](https://github.com/seashoresky/HzyCredit)
[CyberPrisoner](https://github.com/seashoresky/HzyCyber)
注意事项：CyberPrisoner试题有socket_version和database_version两个分支
部署链接：[socket_version](https://6336b10ffe9e2c54d06a66fe--harmonious-croissant-07278b.netlify.app/)

**Comment by chenyanzz** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
