### ISSUE TITLE
林俊光 二面作答

### ISSUE THREAD

**Issue by mini-1235** [QSCTech/2022-Autumn-Round-Two#26]
作答题目：

[RandomCredit](https://github.com/Maurice-1235/qsc-tech-2)

注意事项：
已设置负责人为collaborator，在README.md中已标记重要文档

**Comment by Ag2SO4pro** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
