### ISSUE TITLE
吴佳乐 二面作答

### ISSUE THREAD

**Issue by ghost** [QSCTech/2022-Autumn-Round-Two#27]
作答题目
[q&a](https://github.com/QSCTech/2022-Autumn-Round-Two/tree/main/Q%26A)
[q&a answer](https://github.com/kelarWu/-Q-A)
春招见吧qwq

**Comment by Ag2SO4pro** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
