### ISSUE TITLE
沈柯宇 二面作答

### ISSUE THREAD

**Issue by SteinsHimmer** [QSCTech/2022-Autumn-Round-Two#28]
作答题目
Q&A
h5game半成品
注意事项
1.Q&A aa.html aa.js 1css.css   h5game aaa.html
2.文档 感想.md

**Comment by chenyanzz** [comment]
您好，麻烦附上repo链接！

**Comment by SteinsHimmer** [comment]
https://github.com/himmer1/himmergit

**Comment by ADSR1042** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
