### ISSUE TITLE
王子正 二面作答

### ISSUE THREAD

**Issue by tmplog** [QSCTech/2022-Autumn-Round-Two#29]
Q&A
RandomCredit
H5-Game
已添加出题人为collaborator

**Comment by chenyanzz** [comment]
肝帝，我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。

**Comment by tmplog** [comment]
Q&A：http://47.113.222.130:3100/
(白嫖了阿里云）
