### ISSUE TITLE
董展辰 二面作答

### ISSUE THREAD

**Issue by Cyclohexatriene** [QSCTech/2022-Autumn-Round-Two#3]
作答题目：
<a href=https://github.com/dzcdzcdzc/What-is-JPEG>What-is-JPEG</a>

注意事项：
代码在`[main]/sourcecode.cpp`，文档在`[main]/doc.md`。
另附上了完整的Visual Studio解决方案文件，在`[main]/What is JPEG/`文件夹下。

**Comment by chenyanzz** [comment]
我们已经收到您的提交！祝您二面顺利
