### ISSUE TITLE
王裕涵  二面作答

### ISSUE THREAD

**Issue by cabbagewyh** [QSCTech/2022-Autumn-Round-Two#30]
作答题目：
[Q&A](https://github.com/QSCTech/2022-Autumn-Round-Two/tree/main/Q%26A)
注意事项：
本人用户名为：cabbagewyh
本次作答代码在我的[个人主页](https://github.com/cabbagewyh/-)
该仓库属性为public
仓库中仅有一个main分支
全部代码在[my-first-website.html](https://github.com/cabbagewyh/-/tree/main/my-first-website.html)文档内
html代码在[index.html](https://github.com/cabbagewyh/-/blob/main/my-first-website.html/index.html)内
css代码在styles文件夹的[style.css](https://github.com/cabbagewyh/-/blob/main/my-first-website.html/styles/style.css)文档内
javascript代码在scripts文件夹的[main.js](https://github.com/cabbagewyh/-/blob/main/my-first-website.html/scripts/main.js)文档内
安装Prettier插件的截图在images文件夹的[Prettier插件.jpg](https://github.com/cabbagewyh/-/blob/main/my-first-website.html/images/Prettier%E6%8F%92%E4%BB%B6.jpg)文档内
关于本题作答中的参考资料和做题感想在[README.md](https://github.com/cabbagewyh/-/blob/main/README.md)

**Comment by chenyanzz** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
