### ISSUE TITLE
谢科晋 二面作答

### ISSUE THREAD

**Issue by Cillo-x** [QSCTech/2022-Autumn-Round-Two#31]
作答题目:
[What_is_JPEg](https://github.com/Cillo-x/What_is_JPEG)

注意事项：
1.代码与文档都在master分支下
2.主函数是main.py;文档是文档.txt

**Comment by IsshikiHugh** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
