### ISSUE TITLE
徐靖腾 二面作答

### ISSUE THREAD

**Issue by 2t7m22d** [QSCTech/2022-Autumn-Round-Two#32]
作答题目：
[What-is-JPEG](https://github.com/2t7m22d/qsc_jpeg)

注意事项：
代码是jpeg.cpp，README.md文档是回答问题，document.md文档是注释文档

**Comment by IsshikiHugh** [comment]
我们已有权限检视您的仓库，感谢参加求是潮 2022 秋纳二面，预祝面试顺利~
