### ISSUE TITLE
楼芷杉 二面作答

### ISSUE THREAD

**Issue by zhishanlou** [QSCTech/2022-Autumn-Round-Two#33]
作答题目：
[Q&A]

注意事项：
代码在html,js,css文件中，文档在md文件中

**Comment by zhishanlou** [comment]
图片在初始Q-A.md中（png 加载异常）

**Comment by chenyanzz** [comment]
您好请提供repo的链接谢谢！

**Comment by zhishanlou** [comment]
https://github.com/zhishanlou/Q-A/tree/main

**Comment by IsshikiHugh** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
