### ISSUE TITLE
许佳阳 二面作答

### ISSUE THREAD

**Issue by 1339354001** [QSCTech/2022-Autumn-Round-Two#34]
[Q&A](https://github.com/1339354001/Q-A)

注意事项：代码在“Q&A.html”、“main.js”、“style.css”文件中

[h5](https://github.com/1339354001/h5)

注意事项：代码在“game.html”、“main.js”、“style.css”文件中

**Comment by chenyanzz** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
