### ISSUE TITLE
夏裕诚 二面作答

### ISSUE THREAD

**Issue by Meteors27** [QSCTech/2022-Autumn-Round-Two#35]
作答题目：RandomCredit
[Meteors27/QSC2022Enrollment-RandomCredit](https://github.com/Meteors27/QSC2022Enrollment-RandomCredit)

**Comment by Meteors27** [comment]
心路历程详见Notes.md

**Comment by chenyanzz** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
