### ISSUE TITLE
顾格非 二面作答

### ISSUE THREAD

**Issue by Frankgu3528** [QSCTech/2022-Autumn-Round-Two#37]
作答题目：
[h5-game](https://github.com/ZJU-FrankGu/qsc-intervie) 

注意事项：
最后的游戏发布在：[戳这里](https://frankgu.top/qsc-intervie/)
感想写在`README`里  (真的有好多想说的QAQ)
Question&reference写在`Question.md`里
代码在主仓库`main`下

**Comment by chenyanzz** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
