### ISSUE TITLE
彭一炜 二面作答

### ISSUE THREAD

**Issue by psc03** [QSCTech/2022-Autumn-Round-Two#38]
作答题目：
[Q&A](https://github.com/psc03/qsc)

注意事项：
代码在 Untitled-1.html和scripts/main.js和styles/sty.css ，文档在 感想.md

**Comment by Ag2SO4pro** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
