### ISSUE TITLE
肖一鸣 二面作答

### ISSUE THREAD

**Issue by Winfred666** [QSCTech/2022-Autumn-Round-Two#4]
作答题目：
[h5-game](https://github.com/Winfred666/AnswerToQSCTech/tree/main/h5_game)

注意事项：
代码在h5_game/game.html中，文档在h5_game/附加文档.md中

**Comment by ADSR1042** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
