### ISSUE TITLE
魏子舒 二面作答

### ISSUE THREAD

**Issue by huxibu-alkyimyia** [QSCTech/2022-Autumn-Round-Two#40]
Q&A(https://github.com/huxibu-alkyimyia/QSCTech_2022_Autumn/tree/main/Q%26A)
Cyber_prisoner(https://github.com/huxibu-alkyimyia/QSCTech_2022_Autumn/tree/main/Cyber_Prisoner)

**Comment by chenyanzz** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
