### ISSUE TITLE
陈逸航 二面作答

### ISSUE THREAD

**Issue by sqc-cyh** [QSCTech/2022-Autumn-Round-Two#7]
作答题目：
h5-game

注意事项：
文件夹里有多个html文件，请全部下载后打开初始.html开始游玩；
代码在https://github.com/hangTop/-
文档也在https://github.com/hangTop/-
代码在链接里点进去文件夹的【具体代码】文件夹中，
文档单独列在外面

**Comment by ADSR1042** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
