### ISSUE TITLE
贵司的笔试形式这么超前？😂

### ISSUE THREAD

**Issue by WangNianyi2001** [QSCTech/2022-Autumn-Round-Two#8]
从主页点进来，大概搂了一眼内容，好家伙涉猎得可太广了。
我目前在中传读游戏开发，我觉得您这五道题能顶我们系两年的教学大纲（指对于什么都不会的大一纯新生而言）。

**Comment by Ag2SO4pro** [comment]
您好！感谢您路过留下的反馈~这个仓库里的二面题基本上都提供了相关的文档，旨在鼓励面试者去学习新的技术并加以应用，而不是考察面试者现有的技术水平。虽然看上去涉猎很广，但难度有高低之分，面试者也只需要根据自己的自身情况选择其中的一道题进行钻研即可。其实没有看上去那么难hhh

**Comment by Dimlitter** [comment]
您好，关于您的疑惑，我们的解答如下:

1、我们注重考察的并不是题目结果的最终完成度，而是在完成题目过程当中展现出来的自我学习能力和解决问题的能力，所以在题目当中设置了较长的学习路径来区分考察受试者们的学习能力。

2、我们的题目设计是选择感兴趣的任意一道题目即可，因此无疑需要囊括比较广的方面来确保受试者们都能找到自己感兴趣的方向。

好了写到这里token居然抢先我一步comment了我就不多解释了hhh

希望您对我们的解答满意！

**Comment by RalXYZ** [comment]
@WangNianyi2001 
感谢你的关注！
我们这边不是公司，而是一个学生组织（社团），大家凭兴趣来玩的。  
如果你想玩玩的话，可以来做这些题目，但感觉这里可能并不一定适合你。
我看了下你的项目和简历。如果你对计算机核心基础知识感兴趣，可以在网上找找浙大计院数据库课程的幻灯片和大作业，对计科基础能力的提升很有帮助；如果对 C/C++ 工程和 modern C++ 感兴趣，可以去看看 [postgres 的实现](https://github.com/postgres/postgres) 和 [cppreference](https://zh.cppreference.com/w/cpp)。

**Comment by WangNianyi2001** [comment]
> 面试者也只需要根据自己的自身情况选择其中的一道题进行钻研即可。

@Ag2SO4pro 啊原来只要选一道，如此人性化，善哉！
我昨天晚上闲来做了做 Q&A，然后发现我的空闲时间不足以支持我做完五道题，遂删目录睡觉了（（（
