### ISSUE TITLE
方博真 二面作答

### ISSUE THREAD

**Issue by fangbozhen** [QSCTech/2022-Autumn-Round-Two#9]
作答题目
[What-is-JPEG](https://github.com/fangbozhen/JPEG-encoding)

注意事项：
代码在main分支下，文档都在[doc/](https://github.com/fangbozhen/JPEG-encoding/tree/main/doc)中
private repo，其他人无法访问，已经添加负责人为协作者
希望能在9.29面试（虽然国庆都有空），晚课或晚课后时间都可以

**Comment by IsshikiHugh** [comment]
我们已有权限检视您的仓库，感谢您参加求是潮 2022 秋纳二面，预祝您面试顺利。
